//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFS2013BIAdmin.Console.WSControleCenter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", ConfigurationName="WSControleCenter.WarehouseControlWebServiceSoap")]
    public interface WarehouseControlWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/TakeWa" +
            "rehouseProcessingOffline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus TakeWarehouseProcessingOffline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/TakeWa" +
            "rehouseProcessingOffline", ReplyAction="*")]
        System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus> TakeWarehouseProcessingOfflineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/BringW" +
            "arehouseProcessingOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus BringWarehouseProcessingOnline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/BringW" +
            "arehouseProcessingOnline", ReplyAction="*")]
        System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus> BringWarehouseProcessingOnlineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/TakeAn" +
            "alysisProcessingOffline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus TakeAnalysisProcessingOffline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/TakeAn" +
            "alysisProcessingOffline", ReplyAction="*")]
        System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus> TakeAnalysisProcessingOfflineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/BringA" +
            "nalysisProcessingOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus BringAnalysisProcessingOnline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/BringA" +
            "nalysisProcessingOnline", ReplyAction="*")]
        System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus> BringAnalysisProcessingOnlineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/Change" +
            "Setting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChangeSetting(string settingId, string newValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/Change" +
            "Setting", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChangeSettingAsync(string settingId, string newValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/GetSet" +
            "tings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WarehouseJobBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HostedWarehouseJobGroupOfWarehouseJobExecutionDetails))]
        TFS2013BIAdmin.Console.WSControleCenter.WarehouseSettings GetSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/GetSet" +
            "tings", ReplyAction="*")]
        System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.WarehouseSettings> GetSettingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/Proces" +
            "sWarehouse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WarehouseJobBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HostedWarehouseJobGroupOfWarehouseJobExecutionDetails))]
        bool ProcessWarehouse(string collectionName, string jobName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/Proces" +
            "sWarehouse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ProcessWarehouseAsync(string collectionName, string jobName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/Proces" +
            "sAnalysisDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WarehouseJobBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HostedWarehouseJobGroupOfWarehouseJobExecutionDetails))]
        bool ProcessAnalysisDatabase(TFS2013BIAdmin.Console.WSControleCenter.AnalysisDatabaseProcessingType processingType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/Proces" +
            "sAnalysisDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ProcessAnalysisDatabaseAsync(TFS2013BIAdmin.Console.WSControleCenter.AnalysisDatabaseProcessingType processingType);
        
        // CODEGEN: Generating message contract since message GetProcessingStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/GetPro" +
            "cessingStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WarehouseJobBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HostedWarehouseJobGroupOfWarehouseJobExecutionDetails))]
        TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusResponse GetProcessingStatus(TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/GetPro" +
            "cessingStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusResponse> GetProcessingStatusAsync(TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/SetWar" +
            "ehouseJobEnabledState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WarehouseJobBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HostedWarehouseJobGroupOfWarehouseJobExecutionDetails))]
        bool SetWarehouseJobEnabledState(string collectionName, string jobName, TFS2013BIAdmin.Console.WSControleCenter.TeamFoundationJobEnabledState state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/SetWar" +
            "ehouseJobEnabledState", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SetWarehouseJobEnabledStateAsync(string collectionName, string jobName, TFS2013BIAdmin.Console.WSControleCenter.TeamFoundationJobEnabledState state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/SetAna" +
            "lysisJobEnabledState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WarehouseJobBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HostedWarehouseJobGroupOfWarehouseJobExecutionDetails))]
        bool SetAnalysisJobEnabledState(TFS2013BIAdmin.Console.WSControleCenter.TeamFoundationJobEnabledState state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/SetAna" +
            "lysisJobEnabledState", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SetAnalysisJobEnabledStateAsync(TFS2013BIAdmin.Console.WSControleCenter.TeamFoundationJobEnabledState state);
        
        // CODEGEN: Generating message contract since message GetJobPropertiesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/GetJob" +
            "Properties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WarehouseJobBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HostedWarehouseJobGroupOfWarehouseJobExecutionDetails))]
        TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesResponse GetJobProperties(TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/GetJob" +
            "Properties", ReplyAction="*")]
        System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesResponse> GetJobPropertiesAsync(TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/Proces" +
            "sDefaultDimensionsForExpandedCapacity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WarehouseJobBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HostedWarehouseJobGroupOfWarehouseJobExecutionDetails))]
        bool ProcessDefaultDimensionsForExpandedCapacity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03/Proces" +
            "sDefaultDimensionsForExpandedCapacity", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ProcessDefaultDimensionsForExpandedCapacityAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public enum OnlineStatus {
        
        /// <remarks/>
        Started,
        
        /// <remarks/>
        Stopping,
        
        /// <remarks/>
        Stopped,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class WarehouseSettings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WarehouseSetting runIntervalSecondsField;
        
        private WarehouseSetting incrementalProcessIntervalSecondsField;
        
        private WarehouseSetting fullProcessIntervalSecondsField;
        
        private WarehouseSetting dailyFullProcessingTimeField;
        
        private WarehouseSetting maxParallelASProcessingCommandsField;
        
        private WarehouseSetting analysisSchemaUpdateWaitSecondsField;
        
        private WarehouseSetting schemaUpdateWaitSecondsField;
        
        private WarehouseSetting dataUpdateWaitSecondsField;
        
        private WarehouseSetting warehouseCommandSqlTimeoutField;
        
        private WarehouseSetting analysisServicesProcessingTimeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WarehouseSetting RunIntervalSeconds {
            get {
                return this.runIntervalSecondsField;
            }
            set {
                this.runIntervalSecondsField = value;
                this.RaisePropertyChanged("RunIntervalSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WarehouseSetting IncrementalProcessIntervalSeconds {
            get {
                return this.incrementalProcessIntervalSecondsField;
            }
            set {
                this.incrementalProcessIntervalSecondsField = value;
                this.RaisePropertyChanged("IncrementalProcessIntervalSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public WarehouseSetting FullProcessIntervalSeconds {
            get {
                return this.fullProcessIntervalSecondsField;
            }
            set {
                this.fullProcessIntervalSecondsField = value;
                this.RaisePropertyChanged("FullProcessIntervalSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public WarehouseSetting DailyFullProcessingTime {
            get {
                return this.dailyFullProcessingTimeField;
            }
            set {
                this.dailyFullProcessingTimeField = value;
                this.RaisePropertyChanged("DailyFullProcessingTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public WarehouseSetting MaxParallelASProcessingCommands {
            get {
                return this.maxParallelASProcessingCommandsField;
            }
            set {
                this.maxParallelASProcessingCommandsField = value;
                this.RaisePropertyChanged("MaxParallelASProcessingCommands");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public WarehouseSetting AnalysisSchemaUpdateWaitSeconds {
            get {
                return this.analysisSchemaUpdateWaitSecondsField;
            }
            set {
                this.analysisSchemaUpdateWaitSecondsField = value;
                this.RaisePropertyChanged("AnalysisSchemaUpdateWaitSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public WarehouseSetting SchemaUpdateWaitSeconds {
            get {
                return this.schemaUpdateWaitSecondsField;
            }
            set {
                this.schemaUpdateWaitSecondsField = value;
                this.RaisePropertyChanged("SchemaUpdateWaitSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public WarehouseSetting DataUpdateWaitSeconds {
            get {
                return this.dataUpdateWaitSecondsField;
            }
            set {
                this.dataUpdateWaitSecondsField = value;
                this.RaisePropertyChanged("DataUpdateWaitSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public WarehouseSetting WarehouseCommandSqlTimeout {
            get {
                return this.warehouseCommandSqlTimeoutField;
            }
            set {
                this.warehouseCommandSqlTimeoutField = value;
                this.RaisePropertyChanged("WarehouseCommandSqlTimeout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public WarehouseSetting AnalysisServicesProcessingTimeout {
            get {
                return this.analysisServicesProcessingTimeoutField;
            }
            set {
                this.analysisServicesProcessingTimeoutField = value;
                this.RaisePropertyChanged("AnalysisServicesProcessingTimeout");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class WarehouseSetting : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private string descriptionField;
        
        private string defaultValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
                this.RaisePropertyChanged("DefaultValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class HostedWarehouseJobGroupOfWarehouseJobProperties : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WarehouseJobProperties[] jobsField;
        
        private string nameField;
        
        private System.Guid idField;
        
        private bool idFieldSpecified;
        
        private TeamFoundationServiceHostStatus statusField;
        
        private string statusReasonField;
        
        public HostedWarehouseJobGroupOfWarehouseJobProperties() {
            this.statusField = TeamFoundationServiceHostStatus.Started;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Job")]
        public WarehouseJobProperties[] Jobs {
            get {
                return this.jobsField;
            }
            set {
                this.jobsField = value;
                this.RaisePropertyChanged("Jobs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TeamFoundationServiceHostStatus.Started)]
        public TeamFoundationServiceHostStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusReason {
            get {
                return this.statusReasonField;
            }
            set {
                this.statusReasonField = value;
                this.RaisePropertyChanged("StatusReason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class WarehouseJobProperties : WarehouseJobBase {
        
        private int runIntervalField;
        
        private TeamFoundationJobEnabledState enabledStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RunInterval {
            get {
                return this.runIntervalField;
            }
            set {
                this.runIntervalField = value;
                this.RaisePropertyChanged("RunInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TeamFoundationJobEnabledState EnabledState {
            get {
                return this.enabledStateField;
            }
            set {
                this.enabledStateField = value;
                this.RaisePropertyChanged("EnabledState");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public enum TeamFoundationJobEnabledState {
        
        /// <remarks/>
        Enabled,
        
        /// <remarks/>
        SchedulesDisabled,
        
        /// <remarks/>
        FullyDisabled,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WarehouseJobProperties))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WarehouseJobExecutionDetails))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public abstract partial class WarehouseJobBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private System.Guid jobIdField;
        
        private bool jobIdFieldSpecified;
        
        private string extensionNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Guid JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("JobId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobIdSpecified {
            get {
                return this.jobIdFieldSpecified;
            }
            set {
                this.jobIdFieldSpecified = value;
                this.RaisePropertyChanged("JobIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ExtensionName {
            get {
                return this.extensionNameField;
            }
            set {
                this.extensionNameField = value;
                this.RaisePropertyChanged("ExtensionName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class WarehouseJobExecutionDetails : WarehouseJobBase {
        
        private WarehouseJobRunInfo lastRunField;
        
        private WarehouseJobRunInfo currentRunField;
        
        private WarehouseJobRunInfo nextRunField;
        
        private ProcessingStatus jobProcessingStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WarehouseJobRunInfo LastRun {
            get {
                return this.lastRunField;
            }
            set {
                this.lastRunField = value;
                this.RaisePropertyChanged("LastRun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WarehouseJobRunInfo CurrentRun {
            get {
                return this.currentRunField;
            }
            set {
                this.currentRunField = value;
                this.RaisePropertyChanged("CurrentRun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public WarehouseJobRunInfo NextRun {
            get {
                return this.nextRunField;
            }
            set {
                this.nextRunField = value;
                this.RaisePropertyChanged("NextRun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProcessingStatus JobProcessingStatus {
            get {
                return this.jobProcessingStatusField;
            }
            set {
                this.jobProcessingStatusField = value;
                this.RaisePropertyChanged("JobProcessingStatus");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class WarehouseJobRunInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultMessageField;
        
        private System.DateTime queueTimeUtcField;
        
        private System.DateTime executionStartTimeUtcField;
        
        private System.DateTime endTimeUtcField;
        
        private TeamFoundationJobResult resultField;
        
        private bool resultFieldSpecified;
        
        private TeamFoundationJobState jobStateField;
        
        private bool jobStateFieldSpecified;
        
        public WarehouseJobRunInfo() {
            this.queueTimeUtcField = new System.DateTime(0);
            this.executionStartTimeUtcField = new System.DateTime(0);
            this.endTimeUtcField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
                this.RaisePropertyChanged("ResultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime QueueTimeUtc {
            get {
                return this.queueTimeUtcField;
            }
            set {
                this.queueTimeUtcField = value;
                this.RaisePropertyChanged("QueueTimeUtc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime ExecutionStartTimeUtc {
            get {
                return this.executionStartTimeUtcField;
            }
            set {
                this.executionStartTimeUtcField = value;
                this.RaisePropertyChanged("ExecutionStartTimeUtc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime EndTimeUtc {
            get {
                return this.endTimeUtcField;
            }
            set {
                this.endTimeUtcField = value;
                this.RaisePropertyChanged("EndTimeUtc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TeamFoundationJobResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResultSpecified {
            get {
                return this.resultFieldSpecified;
            }
            set {
                this.resultFieldSpecified = value;
                this.RaisePropertyChanged("ResultSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TeamFoundationJobState JobState {
            get {
                return this.jobStateField;
            }
            set {
                this.jobStateField = value;
                this.RaisePropertyChanged("JobState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobStateSpecified {
            get {
                return this.jobStateFieldSpecified;
            }
            set {
                this.jobStateFieldSpecified = value;
                this.RaisePropertyChanged("JobStateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public enum TeamFoundationJobResult {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Succeeded,
        
        /// <remarks/>
        PartiallySucceeded,
        
        /// <remarks/>
        Failed,
        
        /// <remarks/>
        Stopped,
        
        /// <remarks/>
        Killed,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        ExtensionNotFound,
        
        /// <remarks/>
        Inactive,
        
        /// <remarks/>
        Disabled,
        
        /// <remarks/>
        JobInitializationError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public enum TeamFoundationJobState {
        
        /// <remarks/>
        Dormant,
        
        /// <remarks/>
        QueuedScheduled,
        
        /// <remarks/>
        Running,
        
        /// <remarks/>
        Paused,
        
        /// <remarks/>
        Pausing,
        
        /// <remarks/>
        Resuming,
        
        /// <remarks/>
        Stopping,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public enum ProcessingStatus {
        
        /// <remarks/>
        Idle = 1,
        
        /// <remarks/>
        SchemaChange = 2,
        
        /// <remarks/>
        DataChange = 4,
        
        /// <remarks/>
        IncrementalAnalysisProcessing = 8,
        
        /// <remarks/>
        FullAnalysisProcessing = 16,
        
        /// <remarks/>
        WaitingForSchemaChange = 32,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public enum TeamFoundationServiceHostStatus {
        
        /// <remarks/>
        Starting,
        
        /// <remarks/>
        Started,
        
        /// <remarks/>
        Stopping,
        
        /// <remarks/>
        Stopped,
        
        /// <remarks/>
        Pausing,
        
        /// <remarks/>
        Paused,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class WarehouseProcessingJobProperties : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HostedWarehouseJobGroupOfWarehouseJobProperties instanceField;
        
        private HostedWarehouseJobGroupOfWarehouseJobProperties[] collectionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HostedWarehouseJobGroupOfWarehouseJobProperties Instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
                this.RaisePropertyChanged("Instance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Collection")]
        public HostedWarehouseJobGroupOfWarehouseJobProperties[] Collections {
            get {
                return this.collectionsField;
            }
            set {
                this.collectionsField = value;
                this.RaisePropertyChanged("Collections");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class WarehouseControlRequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isVerboseOutputField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public WarehouseControlRequestHeader() {
            this.isVerboseOutputField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool IsVerboseOutput {
            get {
                return this.isVerboseOutputField;
            }
            set {
                this.isVerboseOutputField = value;
                this.RaisePropertyChanged("IsVerboseOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HostedWarehouseJobGroupStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class HostedWarehouseJobGroupOfWarehouseJobExecutionDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WarehouseJobExecutionDetails[] jobsField;
        
        private string nameField;
        
        private System.Guid idField;
        
        private bool idFieldSpecified;
        
        private TeamFoundationServiceHostStatus statusField;
        
        private string statusReasonField;
        
        public HostedWarehouseJobGroupOfWarehouseJobExecutionDetails() {
            this.statusField = TeamFoundationServiceHostStatus.Started;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Job")]
        public WarehouseJobExecutionDetails[] Jobs {
            get {
                return this.jobsField;
            }
            set {
                this.jobsField = value;
                this.RaisePropertyChanged("Jobs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TeamFoundationServiceHostStatus.Started)]
        public TeamFoundationServiceHostStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusReason {
            get {
                return this.statusReasonField;
            }
            set {
                this.statusReasonField = value;
                this.RaisePropertyChanged("StatusReason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class HostedWarehouseJobGroupStatus : HostedWarehouseJobGroupOfWarehouseJobExecutionDetails {
        
        private ProcessingStatus jobProcessingStatusField;
        
        private int jobsRunningField;
        
        private int jobsQueuedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProcessingStatus JobProcessingStatus {
            get {
                return this.jobProcessingStatusField;
            }
            set {
                this.jobProcessingStatusField = value;
                this.RaisePropertyChanged("JobProcessingStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int JobsRunning {
            get {
                return this.jobsRunningField;
            }
            set {
                this.jobsRunningField = value;
                this.RaisePropertyChanged("JobsRunning");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int JobsQueued {
            get {
                return this.jobsQueuedField;
            }
            set {
                this.jobsQueuedField = value;
                this.RaisePropertyChanged("JobsQueued");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public partial class WarehouseProcessingStatusDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime requestTimeUtcField;
        
        private OnlineStatus warehouseProcessingOnlineStatusField;
        
        private OnlineStatus analysisProcessingOnlineStatusField;
        
        private ProcessingStatus jobProcessingStatusField;
        
        private int jobsRunningField;
        
        private int jobsQueuedField;
        
        private HostedWarehouseJobGroupStatus instanceField;
        
        private HostedWarehouseJobGroupStatus[] collectionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime RequestTimeUtc {
            get {
                return this.requestTimeUtcField;
            }
            set {
                this.requestTimeUtcField = value;
                this.RaisePropertyChanged("RequestTimeUtc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OnlineStatus WarehouseProcessingOnlineStatus {
            get {
                return this.warehouseProcessingOnlineStatusField;
            }
            set {
                this.warehouseProcessingOnlineStatusField = value;
                this.RaisePropertyChanged("WarehouseProcessingOnlineStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OnlineStatus AnalysisProcessingOnlineStatus {
            get {
                return this.analysisProcessingOnlineStatusField;
            }
            set {
                this.analysisProcessingOnlineStatusField = value;
                this.RaisePropertyChanged("AnalysisProcessingOnlineStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ProcessingStatus JobProcessingStatus {
            get {
                return this.jobProcessingStatusField;
            }
            set {
                this.jobProcessingStatusField = value;
                this.RaisePropertyChanged("JobProcessingStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int JobsRunning {
            get {
                return this.jobsRunningField;
            }
            set {
                this.jobsRunningField = value;
                this.RaisePropertyChanged("JobsRunning");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int JobsQueued {
            get {
                return this.jobsQueuedField;
            }
            set {
                this.jobsQueuedField = value;
                this.RaisePropertyChanged("JobsQueued");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public HostedWarehouseJobGroupStatus Instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
                this.RaisePropertyChanged("Instance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Collection")]
        public HostedWarehouseJobGroupStatus[] Collections {
            get {
                return this.collectionsField;
            }
            set {
                this.collectionsField = value;
                this.RaisePropertyChanged("Collections");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
    public enum AnalysisDatabaseProcessingType {
        
        /// <remarks/>
        Incremental,
        
        /// <remarks/>
        Full,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProcessingStatus", WrapperNamespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", IsWrapped=true)]
    public partial class GetProcessingStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
        public TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlRequestHeader WarehouseControlRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", Order=0)]
        public string serviceHostName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", Order=1)]
        public string jobName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", Order=2)]
        public bool includeOnlineHostsOnly;
        
        public GetProcessingStatusRequest() {
        }
        
        public GetProcessingStatusRequest(TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlRequestHeader WarehouseControlRequestHeader, string serviceHostName, string jobName, bool includeOnlineHostsOnly) {
            this.WarehouseControlRequestHeader = WarehouseControlRequestHeader;
            this.serviceHostName = serviceHostName;
            this.jobName = jobName;
            this.includeOnlineHostsOnly = includeOnlineHostsOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProcessingStatusResponse", WrapperNamespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", IsWrapped=true)]
    public partial class GetProcessingStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TFS2013BIAdmin.Console.WSControleCenter.WarehouseProcessingStatusDetails WarehouseProcessingStatus;
        
        public GetProcessingStatusResponse() {
        }
        
        public GetProcessingStatusResponse(TFS2013BIAdmin.Console.WSControleCenter.WarehouseProcessingStatusDetails WarehouseProcessingStatus) {
            this.WarehouseProcessingStatus = WarehouseProcessingStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJobProperties", WrapperNamespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", IsWrapped=true)]
    public partial class GetJobPropertiesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03")]
        public TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlRequestHeader WarehouseControlRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", Order=0)]
        public string serviceHostName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", Order=1)]
        public string jobName;
        
        public GetJobPropertiesRequest() {
        }
        
        public GetJobPropertiesRequest(TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlRequestHeader WarehouseControlRequestHeader, string serviceHostName, string jobName) {
            this.WarehouseControlRequestHeader = WarehouseControlRequestHeader;
            this.serviceHostName = serviceHostName;
            this.jobName = jobName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJobPropertiesResponse", WrapperNamespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", IsWrapped=true)]
    public partial class GetJobPropertiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Controller/03", Order=0)]
        public TFS2013BIAdmin.Console.WSControleCenter.WarehouseProcessingJobProperties GetJobPropertiesResult;
        
        public GetJobPropertiesResponse() {
        }
        
        public GetJobPropertiesResponse(TFS2013BIAdmin.Console.WSControleCenter.WarehouseProcessingJobProperties GetJobPropertiesResult) {
            this.GetJobPropertiesResult = GetJobPropertiesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WarehouseControlWebServiceSoapChannel : TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WarehouseControlWebServiceSoapClient : System.ServiceModel.ClientBase<TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap>, TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap {
        
        public WarehouseControlWebServiceSoapClient() {
        }
        
        public WarehouseControlWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WarehouseControlWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseControlWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarehouseControlWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus TakeWarehouseProcessingOffline() {
            return base.Channel.TakeWarehouseProcessingOffline();
        }
        
        public System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus> TakeWarehouseProcessingOfflineAsync() {
            return base.Channel.TakeWarehouseProcessingOfflineAsync();
        }
        
        public TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus BringWarehouseProcessingOnline() {
            return base.Channel.BringWarehouseProcessingOnline();
        }
        
        public System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus> BringWarehouseProcessingOnlineAsync() {
            return base.Channel.BringWarehouseProcessingOnlineAsync();
        }
        
        public TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus TakeAnalysisProcessingOffline() {
            return base.Channel.TakeAnalysisProcessingOffline();
        }
        
        public System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus> TakeAnalysisProcessingOfflineAsync() {
            return base.Channel.TakeAnalysisProcessingOfflineAsync();
        }
        
        public TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus BringAnalysisProcessingOnline() {
            return base.Channel.BringAnalysisProcessingOnline();
        }
        
        public System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.OnlineStatus> BringAnalysisProcessingOnlineAsync() {
            return base.Channel.BringAnalysisProcessingOnlineAsync();
        }
        
        public string ChangeSetting(string settingId, string newValue) {
            return base.Channel.ChangeSetting(settingId, newValue);
        }
        
        public System.Threading.Tasks.Task<string> ChangeSettingAsync(string settingId, string newValue) {
            return base.Channel.ChangeSettingAsync(settingId, newValue);
        }
        
        public TFS2013BIAdmin.Console.WSControleCenter.WarehouseSettings GetSettings() {
            return base.Channel.GetSettings();
        }
        
        public System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.WarehouseSettings> GetSettingsAsync() {
            return base.Channel.GetSettingsAsync();
        }
        
        public bool ProcessWarehouse(string collectionName, string jobName) {
            return base.Channel.ProcessWarehouse(collectionName, jobName);
        }
        
        public System.Threading.Tasks.Task<bool> ProcessWarehouseAsync(string collectionName, string jobName) {
            return base.Channel.ProcessWarehouseAsync(collectionName, jobName);
        }
        
        public bool ProcessAnalysisDatabase(TFS2013BIAdmin.Console.WSControleCenter.AnalysisDatabaseProcessingType processingType) {
            return base.Channel.ProcessAnalysisDatabase(processingType);
        }
        
        public System.Threading.Tasks.Task<bool> ProcessAnalysisDatabaseAsync(TFS2013BIAdmin.Console.WSControleCenter.AnalysisDatabaseProcessingType processingType) {
            return base.Channel.ProcessAnalysisDatabaseAsync(processingType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusResponse TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap.GetProcessingStatus(TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusRequest request) {
            return base.Channel.GetProcessingStatus(request);
        }
        
        public TFS2013BIAdmin.Console.WSControleCenter.WarehouseProcessingStatusDetails GetProcessingStatus(TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlRequestHeader WarehouseControlRequestHeader, string serviceHostName, string jobName, bool includeOnlineHostsOnly) {
            TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusRequest inValue = new TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusRequest();
            inValue.WarehouseControlRequestHeader = WarehouseControlRequestHeader;
            inValue.serviceHostName = serviceHostName;
            inValue.jobName = jobName;
            inValue.includeOnlineHostsOnly = includeOnlineHostsOnly;
            TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusResponse retVal = ((TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap)(this)).GetProcessingStatus(inValue);
            return retVal.WarehouseProcessingStatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusResponse> TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap.GetProcessingStatusAsync(TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusRequest request) {
            return base.Channel.GetProcessingStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusResponse> GetProcessingStatusAsync(TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlRequestHeader WarehouseControlRequestHeader, string serviceHostName, string jobName, bool includeOnlineHostsOnly) {
            TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusRequest inValue = new TFS2013BIAdmin.Console.WSControleCenter.GetProcessingStatusRequest();
            inValue.WarehouseControlRequestHeader = WarehouseControlRequestHeader;
            inValue.serviceHostName = serviceHostName;
            inValue.jobName = jobName;
            inValue.includeOnlineHostsOnly = includeOnlineHostsOnly;
            return ((TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap)(this)).GetProcessingStatusAsync(inValue);
        }
        
        public bool SetWarehouseJobEnabledState(string collectionName, string jobName, TFS2013BIAdmin.Console.WSControleCenter.TeamFoundationJobEnabledState state) {
            return base.Channel.SetWarehouseJobEnabledState(collectionName, jobName, state);
        }
        
        public System.Threading.Tasks.Task<bool> SetWarehouseJobEnabledStateAsync(string collectionName, string jobName, TFS2013BIAdmin.Console.WSControleCenter.TeamFoundationJobEnabledState state) {
            return base.Channel.SetWarehouseJobEnabledStateAsync(collectionName, jobName, state);
        }
        
        public bool SetAnalysisJobEnabledState(TFS2013BIAdmin.Console.WSControleCenter.TeamFoundationJobEnabledState state) {
            return base.Channel.SetAnalysisJobEnabledState(state);
        }
        
        public System.Threading.Tasks.Task<bool> SetAnalysisJobEnabledStateAsync(TFS2013BIAdmin.Console.WSControleCenter.TeamFoundationJobEnabledState state) {
            return base.Channel.SetAnalysisJobEnabledStateAsync(state);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesResponse TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap.GetJobProperties(TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesRequest request) {
            return base.Channel.GetJobProperties(request);
        }
        
        public TFS2013BIAdmin.Console.WSControleCenter.WarehouseProcessingJobProperties GetJobProperties(TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlRequestHeader WarehouseControlRequestHeader, string serviceHostName, string jobName) {
            TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesRequest inValue = new TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesRequest();
            inValue.WarehouseControlRequestHeader = WarehouseControlRequestHeader;
            inValue.serviceHostName = serviceHostName;
            inValue.jobName = jobName;
            TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesResponse retVal = ((TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap)(this)).GetJobProperties(inValue);
            return retVal.GetJobPropertiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesResponse> TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap.GetJobPropertiesAsync(TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesRequest request) {
            return base.Channel.GetJobPropertiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesResponse> GetJobPropertiesAsync(TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlRequestHeader WarehouseControlRequestHeader, string serviceHostName, string jobName) {
            TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesRequest inValue = new TFS2013BIAdmin.Console.WSControleCenter.GetJobPropertiesRequest();
            inValue.WarehouseControlRequestHeader = WarehouseControlRequestHeader;
            inValue.serviceHostName = serviceHostName;
            inValue.jobName = jobName;
            return ((TFS2013BIAdmin.Console.WSControleCenter.WarehouseControlWebServiceSoap)(this)).GetJobPropertiesAsync(inValue);
        }
        
        public bool ProcessDefaultDimensionsForExpandedCapacity() {
            return base.Channel.ProcessDefaultDimensionsForExpandedCapacity();
        }
        
        public System.Threading.Tasks.Task<bool> ProcessDefaultDimensionsForExpandedCapacityAsync() {
            return base.Channel.ProcessDefaultDimensionsForExpandedCapacityAsync();
        }
    }
}
